/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'manu' at '4/9/18 12:15 PM' with Gradle 3.0
 *
 * @author manu, @date 4/9/18 12:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
